[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "FoamFunctions"
version = "0.1"
dependencies = ["numpy"]

[tool.setuptools]
packages = ["FoamFunctions"]

